config {  type: "view" }
SELECT
 * EXCEPT(ROW,record_deleted,bg,cyber_security_level),
 CASE 
 WHEN bg_code='10B' THEN 'CDA'
 WHEN bg_code='20B' THEN 'PTS'
 WHEN bg_code='30B' THEN 'THS'
 WHEN bg_code='40B' THEN 'VIS'
 ELSE bg
 END AS bg
FROM 
 (
   SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY id ORDER BY sync_time DESC) AS ROW,
   FROM ${ref("MP_GETVIEW_Projects_001")} 
 )
WHERE ROW=1 AND record_deleted =FALSE